#！！！极简版！！！ 先关闭mosdns再用 具体操作查看备用-mosdns相关
proxies:
proxy-providers:
 
  机场:
    type: http
    url: "订阅链接地址，填写在双引号以内"
    path: ./proxy_providers/机场.yaml
    interval: 10800
    
proxy-groups:
  - name: 节点选择
    type: select
    use:
      - 机场
    
rule:
  - GEOIP,private,DIRECT
  - GEOSITE,private,DIRECT

  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT

  - GEOSITE,!CN,节点选择
  - GEOIP,!CN,节点选择
  
  - MATCH,节点选择