#！！！极简版！！！ 
proxies:
proxy-providers:
 
  机场:
    type: http
    url: "订阅链接地址，填写在双引号以内"
    path: ./proxy_providers/机场.yaml
    interval: 86400
    
proxy-groups:
  - name: 节点选择
    type: select
    use:
      - 机场

rule-providers:

  userDirect:
    type: file
    behavior: classical
    path: ./rule_providers/userDirect.yaml

  userProxy:
    type: file
    behavior: classical
    path: ./rule_providers/userProxy.yaml
    
rule:
  - GEOIP,private,DIRECT
  - GEOSITE,private,DIRECT

  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  
  - MATCH,节点选择