proxies:
proxy-groups:
  - name: "LLYCORIS"
    type: select
    use:
      - provide
proxy-providers:
  provide:
    type: file
    path: ./assets/akun.yaml
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
rules:
  - MATCH,LLYCORIS