#-----------------------------------------------------------------------
#警告：如果你想要修改除了订阅链接的其他部分，务必对Meta内核的配置规则熟练掌握
#如果你想手动添加代理或直连的地址，建议添加到userProxy和userDriect
#如果你想删预置的userProxy和userDriect，务必要删除template文件
#里面对应的nameserver-policy，否则内核将无法启动
#注意：预置规则已经很完善，如果你使用自己的配置，出了问题请自己排查，不要问作者
#-----------------------------------------------------------------------
proxies:
#自己单独的节点/自建节点/免流方案可以往这里写一下，参见教程里面的格式
proxy-providers:
  
  机场1:
    type: http
    url: "订阅链接"
    path: ./proxy_providers/机场1.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900
  机场2:
    type: http
    url: "订阅链接"
    path: ./proxy_providers/机场2.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900
  机场3:
    type: http
    url: "订阅链接"
    path: ./proxy_providers/机场3.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900
  机场4:
    type: http
    url: "订阅链接"
    path: ./proxy_providers/机场4.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900    
  机场5:
    type: http
    url: "订阅链接"
    path: ./proxy_providers/机场5.yaml
    interval: 10800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900   

#-------------------------------------------------------------------
#data/clash/proxy-provider里面有白嫖节点可以使用，也欢迎提交更多白嫖节点
#使用p核时，如果无法正常更新订阅，请打开proxy provider 里面的机场yaml配置文件查看
#如果是乱码，需要自己在订阅链接结尾加上 &flag=clash  强制订阅服务器下发clash的配置文件
# 机场2 机场1 机场3为机场名，可以更换，要换必须全换，建议使用编辑器的查找替换功能避免遗漏
#-------------------------------------------------------------------
proxy-groups:
  - name: 机场
    type: select
    proxies:
      - 机场1
      - 机场2
      - 机场3
      - 机场4
      - 机场5
      - 美国节点
      - 负载均衡-大带宽
      - 负载均衡-优IP

  - name: 机场1
    type: select
    use:
      - 机场1

  - name: 机场2
    type: select
    use:
      - 机场2

  - name: 机场3
    type: select
    use:
      - 机场3
      
  - name: 机场4
    type: select
    use:
      - 机场4

  - name: 机场5
    type: select
    use:
      - 机场5


  - name: 美国节点
    type: select
    use:
      - 机场1
      - 机场2
      - 机场3
      - 机场4
      - 机场5
    filter: '美国|USA|美國|us|US'
#meta的特性，如果你经常使用某个地区节点可以使用过滤器便于选择 美国节点 可以改为其他
#但是要改就得全改，建议使用编辑器的替换功能防止遗漏。过滤器内容用 | 分割，支持通配符

  - name: 负载均衡-大带宽
    type: load-balance
    use:
      - 机场1
    url: 'http://www.gstatic.com/generate_204'
    interval: 900
    filter: '美国|USA|美國'
    lazy: true
    strategy: consistent-hashing

  - name: 负载均衡-优IP
    type: load-balance
    use:
      - 机场4
    url: 'http://www.gstatic.com/generate_204'
    interval: 900
    filter: '美国|USA|美國'
    lazy: true
    strategy: consistent-hashing


  - name: 墙内网址
    type: select
    proxies:
      - DIRECT
      - REJECT
      - 机场

  - name: 广告屏蔽
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: 其他
    type: select
    proxies:
      - 机场
      - 墙内网址
#用户自定义规则，文件在data/clash/rule-provider/
#需要的自己写入，格式参照 备用 文件夹里面的clash官方文档
#有一些规则已经预装但是未使用 比如fcm相关规则

rule-providers:

  userDirect:
    type: file
    behavior: classical
    path: ./rule_providers/userDirect.yaml

  userProxy:
    type: file
    behavior: classical
    path: ./rule_providers/userProxy.yaml

rules:
  - RULE-SET,userProxy,机场
  - RULE-SET,userDirect,墙内网址
  
  - GEOIP,private,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,category-ads-all,广告屏蔽

  - GEOSITE,CN,墙内网址
  - GEOIP,CN,墙内网址

  - GEOSITE,!CN,机场
  - GEOIP,!CN,机场
  
  - MATCH,其他