#说明：只需要在119-188行的url里面填写订阅地址，在网页仪表盘拉到最底下对应名字的组点开，update一次就可以用了。如果不能update，默认节点选择香港
#如果你有自己的配置，也可以自己替换进去，但首先你应该清楚需要动哪里
mixed-port: 7890
tproxy-port: 7891

tun:
  enable: false
  stack: system
  dns-hijack:
    - '0.0.0.0:53'
  auto-route: true
  auto-detect-interface: true

unified-delay: false
geodata-mode: true
tcp-concurrent: false

allow-lan: true
mode: rule
log-level: debug
ipv6: false
udp: true

external-controller: 0.0.0.0:9090
external-ui: ui
secret: ""

profile:
  store-fake-ip: true
sniffer:
  enable: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.lan'
    - '+.cn'
    - '+.10010.com'
    - '+.chinaunicom.com'
    - '+.baidu.com'
    - '*.alipay.com'
    - '*.alipayobjects.com'
    - '*.jijifun.com'
    - 'connect.rom.miui.com'
    - 'localhost.ptlogin2.qq.com'
    - '+.msftnsci.com'
    - '+.msftconnecttest.com'
    - 'dl.google.com'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://dns.adguard.com/dns-query#自动选择
    - https://dns.google/dns-query#自动选择
    - https://cloudflare-dns.com/dns-query#自动选择
  fallback-filter:
        geoip: true
        geoip-code: CN
        geosite: 
            - GFW
            - GREATFIRE

proxies:
#锚点
p: &p
  type: http
  interval: 1800
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300

c: &c
  type: http
  behavior: classical
  interval: 86400

#改下面代理提供商的名字的话，这里面的名字也需要一并修改
u: &u
  type: select
  use:
    - test
    - test1
    - test2
    - test3
    - test4
    - test5
    - test6
    - test7
    - test8
    - test9
    - test10
    - test11
    - test12

pr: &pr
  type: select
  proxies:
    - 默认
    - 自动选择
    - 中国
    - 香港
    - 台湾
    - 日本
    - 新加坡
    - 美国
    - 其它地区
    - 专线
    - 全部
    - 直连
    - 拦截/阻断
    - 跳过匹配

proxy-providers:

  test: #这是名字，可以随便改，喜欢就行，但是需要一并改动上面的锚点里面的名字
    <<: *p
    url: "这里写订阅，一个机场写一个里面，下面以此类推"
    path: ./proxy_providers/test.yaml
    #path一般不需要改，反正又看不到
    
    #如果觉得不好看，也可以把下面的多余的删掉，use的锚点里面的提供商删掉就行

  test1:
    <<: *p
    url: ""
    path: ./proxy_providers/test1.yaml

  test2:
    <<: *p
    url: ""
    path: ./proxy_providers/test2.yaml

  test3:
    <<: *p
    url: ""
    path: ./proxy_providers/test3.yaml

  test4:
    <<: *p
    url: ""
    path: ./proxy_providers/test4.yaml

  test5:
    <<: *p
    url: ""
    path: ./proxy_providers/test5.yaml

  test6:
    <<: *p
    url: ""
    path: ./proxy_providers/test6.yaml

  test7:
    <<: *p
    url: ""
    path: ./proxy_providers/test7.yaml

  test8:
    <<: *p
    url: ""
    path: ./proxy_providers/test8.yaml

  test9:
    <<: *p
    url: ""
    path: ./proxy_providers/test9.yaml

  test10:
    <<: *p
    url: ""
    path: ./proxy_providers/test10.yaml

  test11:
    <<: *p
    url: ""
    path: ./proxy_providers/test11.yaml

  test12:
    <<: *p
    url: ""
    path: ./proxy_providers/test12.yaml


proxy-groups:

  - name: 默认
    type: select
    proxies:
      - DIRECT
      - 中国
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - 专线
      - 全部

  - name: Google
    <<: *pr

  - name: Google Voice
    <<: *pr

#社交
  - name: Telegram
    <<: *pr

  - name: Instagram
    <<: *pr

  - name: line
    <<: *pr

  - name: pixiv
    <<: *pr

  - name: ehentai
    <<: *pr

#流媒体

  - name: 哔哩哔哩
    <<: *pr

  - name: 哔哩东南亚
    <<: *pr

  - name: 巴哈姆特
    <<: *pr

  - name: Niconico
    <<: *pr

  - name: YouTube
    <<: *pr

  - name: NETFLIX
    <<: *pr

  - name: Spotify
    <<: *pr

  - name: PayPal
    <<: *pr

#杂七杂八
  - name: 游戏
    <<: *pr

  - name: 微博定位
    <<: *pr

  - name: 国内
    type: select
    proxies:
      - 直连
      - 默认
      - 自动选择
      - 中国
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - 专线
      - 全部
      - 拦截/阻断
      - 跳过匹配

  - name: 其他
    <<: *pr

#分隔，下面是地区分组
  - name: 香港
    filter: "港|香港|HK|HongKong"
    <<: *u

  - name: 台湾
    filter: "台|台湾|TW|Taiwan"
    <<: *u

  - name: 日本
    filter: "日|日本|JP|Japan"
    <<: *u

  - name: 美国
    filter: "美|美国|US|UnitedStates"
    <<: *u

  - name: 新加坡
    filter: "新|新加坡|SG|Singapore"
    <<: *u

  - name: 中国
    filter: "广停|广东|杭州|腾讯云广州|阿里云北京|中国|国内|China"
    <<: *u

  - name: 专线
    filter: "IPLC|IEPL|CN2|GAPN|CUVIP|AIA"
    <<: *u

  - name: 其它地区
    filter: "^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|广停|广东|中国|国内|China|香港|hk|HK|hongkong|台|台湾|TW|taiwan|日本|jp|JP|新加坡|sg|美国|US)).*"
    <<: *u

  - name: 全部
    <<: *u

  - name: 自动选择
    <<: *u
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 10

#汉化一下)？

  - name: 直连
    type: select
    proxies:
      - DIRECT

  - name: 拦截/阻断
    type: select
    proxies:
      - REJECT

  - name: 跳过匹配
    type: select
    proxies:
      - PASS

rule-providers:

  Google:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
    path: ./rule_providers/Google.yaml

  YouTube:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./rule_providers/YouTube.yaml

  YouTubeMusic:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.yaml"
    path: ./rule_providers/YouTubeMusic.yaml

  Telegram:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./rule_providers/Telegram.yaml

  Netflix:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
    path: ./rule_providers/Netflix.yaml

  PayPal:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
    path: ./rule_providers/PayPal.yaml

  Riot:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Riot/Riot.yaml"
    path: ./rule_providers/Riot.yaml

  bilibili:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./rule_providers/BiliBili.yaml

  biliintl:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.yaml"
    path: ./rule_providers/biliintl.yaml

  Bahamut:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml"
    path: ./rule_providers/Bahamut.yaml

  Niconico:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.yaml"
    path: ./rule_providers/Niconico.yaml

  ins:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml"
    path: ./rule_providers/ins.yaml

  Spotify:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml"
    path: ./rule_providers/Spotify.yaml

  pixiv:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Pixiv/Pixiv.yaml"
    path: ./rule_providers/pixiv.yaml

  GV:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.yaml"
    path: ./rule_providers/GV.yaml

  ehentai:
    <<: *c
    url: "https://raw.githubusercontent.com/xishang0128/clash-rules/main/ehentai.yaml"
    path: ./rule_providers/ehentai.yaml

  line:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml"
    path: ./rule_providers/line.yaml

rules:
  - AND,((DST-PORT,5228-5230),(NETWORK,TCP),(DOMAIN-KEYWORD,google)),DIRECT
  - RULE-SET,GV,Google Voice
  - RULE-SET,YouTube,YouTube
  - RULE-SET,YouTubeMusic,YouTube
  - RULE-SET,Google,Google
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Netflix,NETFLIX
  - RULE-SET,PayPal,PayPal
  - RULE-SET,Riot,游戏
  - RULE-SET,biliintl,哔哩东南亚
  - RULE-SET,bilibili,哔哩哔哩
  - RULE-SET,ins,Instagram
  - RULE-SET,line,line
  - RULE-SET,Niconico,Niconico
  - RULE-SET,Bahamut,巴哈姆特
  - RULE-SET,Spotify,Spotify
  - RULE-SET,pixiv,pixiv
  - RULE-SET,ehentai,ehentai
  - DOMAIN,api.weibo.cn,微博定位
  - GEOSITE,CN,国内
  - GEOIP,CN,国内
  - MATCH,其他



















还有一份
proxies:

p: &p
  filter: "^((?!(官网|官址|网址|更新|刷新|购买|加群|不能用)).)*$"
  type: http
  interval: 1800
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300

fb: &fb
  type: fallback
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 10
  use:
    - 一元机场
    - 倾城极速
    - 白嫖

s: &s
  type: select
  use:
    - 一元机场
    - 倾城极速
    - 白嫖

t: &t
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 10
  use:
    - 一元机场
    - 倾城极速
    - 白嫖

pr: &pr
  type: select
  proxies:
    - 🚀 节点选择
    - ♻️ 自动选择
    - 🇸🇬 新加坡节点
    - 🇭🇰 香港节点
    - 🇨🇳 台湾节点
    - 🇯🇵 日本节点
    - 🇺🇲 美国节点
    - 🏳️‍🌈 原生/解锁
    - 🏳️‍⚧️ 其他地区
    - 专线
    - 直连
    - PASS

c: &c
  type: http
  behavior: classical
  interval: 86400

f: &f
  type: file
  behavior: classical

#——————————————————————————————————————————————————

proxy-providers:

  一元机场:
    <<: *p
    url: ""
    path: ./proxy_providers/一元机场.yaml

  倾城极速:
    <<: *p
    url: ""
    path: ./proxy_providers/倾城极速.yaml

  白嫖:
    <<: *p
    url: "https://jetstream.site/api/v1/public/services/41618/55d7412e848eedfb93100a9c56f570f8?client=clash"
    path: ./proxy_providers/白嫖.yaml

#——————————————————————————————————————————————————

proxy-groups:

  - name: DNS
    type: select
    proxies:
      - 🇺🇲 美国节点
      - 🇯🇵 日本节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 新加坡节点
      - 🏳️‍⚧️ 其他地区
      - 直连

  - name: 🚀 节点选择
    type: select
    proxies:
      - 🚧 故障转移
      - ♻️ 自动选择
      - 🇸🇬 新加坡节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🏳️‍🌈 原生/解锁
      - 🏳️‍⚧️ 其他地区
      - 专线
      - 直连

  - name: 专线
    filter: "IPLC|IEPL|CN2|GAPN|CUVIP|AIA|iplc|iepl"
    <<: *s

  - name: 🚧 故障转移
    proxies:
        - 🛵 直连节点
        - ♻️ 自动选择
    <<: *fb

  - name: 🛵 直连节点
    filter: "直连|direct"
    <<: *s

  - name: 🏳️‍🌈 原生/解锁
    filter: "原生|解锁"
    <<: *s

  - name: 🏳️‍⚧️ 其他地区
    filter: "^((?!(🇭🇰|香港|HK|HongKong|Hong Kong|HKG|🇸🇬|新加坡|狮城|Singapore|SG|🇯🇵|日|日本|东京|Japan|JP|🇺🇲|美|美国|US|United States|UnitedStates|America|Korea|KR|🇹🇼|台|台湾|TW|Tai Wan)).)*$"
    <<: *s

  - name: 🇺🇲 美国节点
    filter: "🇺🇲|美|美国|US|United States|UnitedStates|America"
    <<: *fb

  - name: 🇭🇰 香港节点
    filter: "🇭🇰|香港|HK|HongKong|HKG|Hong Kong"
    <<: *t

  - name: 🇨🇳 台湾节点
    filter: "🇹🇼|台|台湾|TW|Tai Wan"
    <<: *t

  - name: 🇸🇬 新加坡节点
    filter: "🇸🇬|新加坡|狮城|Singapore|SG"
    <<: *t

  - name: 🇯🇵 日本节点
    filter: "🇯🇵|日|日本|东京|Japan|JP"
    <<: *t

  - name: ♻️ 自动选择
    <<: *t

#——————————————————————————————————————————————————

  - name: 📢 Google
    <<: *pr

  - name: 📲 Telegram
    <<: *pr

  - name: 📺 Netflix
    <<: *pr

  - name: 📹 YouTube
    <<: *pr

  - name: 🍋 BiliBili
    <<: *pr

  - name: 📙 Ehentai
    <<: *pr

  - name: 🎮 Games
    <<: *pr

  - name: 🪟 Microsoft
    <<: *pr

#——————————————————————————————————————————————————

  - name: 🎯 全球直连
    type: select
    proxies:
      - 直连
      - 🚀 节点选择

  - name: 🍃 广告过滤
    type: select
    proxies:
      - 拦截
      - PASS

  - name: 直连
    type: select
    proxies:
      - DIRECT

  - name: 拦截
    type: select
    proxies:
      - REJECT

#——————————————————————————————————————————————————

rule-providers:

  直连rules:
    <<: *f
    path: ./rule_providers/自定/直连.yaml

  代理rules:
    <<: *f
    path: ./rule_providers/自定/代理.yaml

  Google:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
    path: ./rule_providers/Google.yaml

  GoogleFCM:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml"
    path: ./rule_providers/GoogleFCM.yaml

  YouTube:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./rule_providers/YouTube.yaml

  Microsoft:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./rule_providers/Microsoft.yaml

  Telegram:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./rule_providers/Telegram.yaml

  Netflix:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
    path: ./rule_providers/Netflix.yaml

  GitHub:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml"
    path: ./rule_providers/GitHub.yaml

  BiliBili:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./rule_providers/BiliBili.yaml

  Advertising:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml"
    path: ./rule_providers/Advertising.yaml

  Ehentai:
    <<: *c
    url: "https://raw.githubusercontent.com/xishang0128/clash-rules/main/ehentai.yaml"
    path: ./rule_providers/Ehentai.yaml

  WeChat:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml"
    path: ./rule_providers/WeChat.yaml

  Tencent:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.yaml"
    path: ./rule_providers/Tencent.yaml

  Epic:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml"
    path: ./rule_providers/Epic.yaml

  Steam:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml"
    path: ./rule_providers/Steam.yaml

  EA:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.yaml"
    path: ./rule_providers/EA.yaml

#——————————————————————————————————————————————————

rules:

  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - PROCESS-NAME,clash,REJECT
  - PROCESS-NAME,com.tw.fivexgames.apexlegendsmobile,🎮 Games
  - RULE-SET,代理rules,🚀 节点选择
  - RULE-SET,直连rules,🎯 全球直连
  - RULE-SET,WeChat,🎯 全球直连
  - RULE-SET,Tencent,🎯 全球直连
  - RULE-SET,GoogleFCM,🎯 全球直连
  - RULE-SET,Epic,🎮 Games
  - RULE-SET,Steam,🎮 Games
  - RULE-SET,EA,🎮 Games
  - RULE-SET,Google,📢 Google
  - RULE-SET,YouTube,📹 YouTube
  - RULE-SET,Netflix,📺 Netflix
  - RULE-SET,Microsoft,🪟 Microsoft
  - RULE-SET,GitHub,🪟 Microsoft
  - RULE-SET,Telegram,📲 Telegram
  - RULE-SET,BiliBili,🍋 BiliBili
  - RULE-SET,Ehentai,📙 Ehentai
  - RULE-SET,Advertising,🍃 广告过滤
  - GEOSITE,CN,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🚀 节点选择
















  proxies:
p: &p
  type: http
  interval: 3600
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
c: &c
  type: http
  behavior: classical
  interval: 21600
f: &f
  type: file
  behavior: classical
t: &t
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 10
  use:
    - 机场一
    - 机场二
    - 机场三
    - 机场四
    - 机场五
    - 机场六
g: &g
  type: select
  proxies:
    - 机场一
    - 机场二
    - 机场三
    - 机场四
    - 机场五
    - 机场六
    - 自动选择
    - PASS
    - 直连
    - 香港
    - 台湾
    - 日本
    - 新加坡
    - 美国

proxy-providers:
  
  机场一:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场1.yaml
  机场二:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场2.yaml
  机场三:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场3.yaml
  机场四:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场4.yaml
  机场五:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场5.yaml
  机场六:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场6.yaml
# 机场一,机场二为机场名，可以改名，如果要换名必须全换，否则启动失败

proxy-groups:
  - name: 机场
    <<: *g
  - name: 机场一
    type: select
    use:
      - 机场一
  - name: 机场二
    type: select
    use:
      - 机场二
  - name: 机场三
    type: select
    use:
      - 机场三
  - name: 机场四
    type: select
    use:
      - 机场四
  - name: 机场五
    type: select
    use:
      - 机场五
  - name: 机场六
    type: select
    use:
      - 机场六
  - name: 香港
    filter: "港|香港|HK|HongKong"
    <<: *t
  - name: 台湾
    filter: "台|台湾|TW|Taiwan"
    <<: *t
  - name: 日本
    filter: "日|日本|JP|Japan"
    <<: *t
  - name: 美国
    filter: "美|美国|US|UnitedStates"
    <<: *t
  - name: 新加坡
    filter: "新|新加坡|SG|Singapore|狮城"
    <<: *t  
  - name: 自动选择
    <<: *t
  - name: 游戏
    <<: *g
  - name: 哔哩哔哩
    <<: *g
 
  - name: 广告过滤
    type: select
    proxies:
      - 拦截
      - PASS
      
  - name: 拦截
    type: select
    proxies:
      - REJECT
      
  - name: 直连
    type: select
    proxies:
      - DIRECT

  - name: 国内
    type: select
    proxies:
      - 直连
      - 机场

  - name: 其他
    type: select
    proxies:
      - 机场
      - 国内

rule-providers:
  AD:
    type: http
    behavior: domain
    url: https://anti-ad.net/clash.yaml
    path: ./rule_providers/Ad.yaml
    interval: 21600
  Google:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    path: ./rule_providers/Google.yaml  
  GoogleFCM:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
    path: ./rule_providers/GoogleFCM.yaml
  YouTube:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./rule_providers/YouTube.yaml
  Tencent:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.yaml
    path: ./rule_providers/Tencent.yaml
  WeChat:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml
    path: ./rule_providers/WeChat.yaml
  Game:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
    path: ./rule_providers/Game.yaml
  TikTok:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
    path: ./rule_providers/TikTok.yaml
  BiliBili:
    <<: *c
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./rule_providers/BiliBili.yaml
  AppProxy:
    <<: *f
    path: ./rule_providers/AppProxy.yaml
  AppDirect:
    <<: *f
    path: ./rule_providers/AppDirect.yaml  
  Local:
    <<: *f
    path: ./rule_providers/Locale.yaml 

rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  # 解决Clash会回环
 # - PROCESS-NAME,clash,REJECT # 解决Clash会回环如果打开会导致无法手动更新订阅，只能自动更新
  - RULE-SET,Local,国内,no-resolve
  - RULE-SET,Tencent,国内,no-resolve
  - RULE-SET,WeChat,国内,no-resolve
  - RULE-SET,AD,广告过滤 # 去广告规则，不想用，最前面的加上#号即可
  - RULE-SET,GoogleFCM,机场
  - RULE-SET,YouTube,机场
  - RULE-SET,Game,游戏
  - RULE-SET,Google,机场  
  - RULE-SET,TikTok,机场  
  - RULE-SET,AppProxy,机场
  - RULE-SET,AppDirect,国内
  - RULE-SET,BiliBili,哔哩哔哩
  - GEOSITE,CN,国内,no-resolve
  - GEOIP,CN,国内,no-resolve
  - MATCH,机场
